[package]
name = "ruspell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
regex = "1.10.4"
thiserror = "1.0.58"

[lints]
[lints.rust]
dead_code = { level = "allow", priority = 1 }
[lints.clippy]
nursery = "warn"
pedantic = "warn"
cargo = "warn"

dbg_macro = "warn"
# missing_docs_in_private_items = "warn"
todo = "warn"
unwrap_used = "warn"

redundant_pub_crate = { level = "allow", priority = 1 }
[lints.rustdoc]
all = "warn"
